import os
import shutil
import subprocess
import tempfile
import threading
import time
import uuid
from datetime import datetime, timedelta
from pathlib import Path
from threading import Lock

from config import (
    DOWNLOADS_DIR, COOKIES_FILE, COOKIE_REFRESH_SEC, CHROMIUM_PROFILES,
    YTDLP_LAST_UPDATE_FILE, YTDLP_UPDATE_INTERVAL_DAYS, logger,
)

_cookie_lock = Lock()
_cookie_ready = threading.Event()

def get_ytdlp_version() -> str:
    try:
        result = subprocess.run(
            ["yt-dlp", "--version"],
            capture_output=True, text=True, timeout=10
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"

def should_update_ytdlp() -> bool:
    if not YTDLP_LAST_UPDATE_FILE.exists():
        return True
    try:
        last_update = datetime.fromisoformat(
            YTDLP_LAST_UPDATE_FILE.read_text().strip()
        )
        return datetime.now() - last_update > timedelta(days=YTDLP_UPDATE_INTERVAL_DAYS)
    except Exception:
        return True

def update_ytdlp_background():
    def _update():
        try:
            old_version = get_ytdlp_version()
            logger.info(f"Updating yt-dlp (current: {old_version})...")
            import sys
            result = subprocess.run(
                [sys.executable, "-m", "pip", "install", "--upgrade", "yt-dlp", "--break-system-packages"],
                capture_output=True, text=True, timeout=120
            )
            if result.returncode == 0:
                new_version = get_ytdlp_version()
                YTDLP_LAST_UPDATE_FILE.write_text(datetime.now().isoformat())
                if old_version != new_version:
                    logger.info(f"yt-dlp updated: {old_version} \u2192 {new_version}")
                else:
                    logger.info(f"yt-dlp already latest: {new_version}")
            else:
                logger.warning(f"yt-dlp update failed: {result.stderr[:200]}")
        except Exception as e:
            logger.error(f"yt-dlp auto-update error: {e}")
    thread = threading.Thread(target=_update, daemon=True)
    thread.start()

def _chromium_db_exists(browser: str) -> bool:
    base = CHROMIUM_PROFILES.get(browser)
    if not base: return False
    for sub in ("Default", "Profile 1", "Profile 2", ""):
        db = base / sub / "Network" / "Cookies"
        if db.exists(): return True
        db2 = base / sub / "Cookies"
        if db2.exists(): return True
    return False

def _copy_locked_db(db_path: Path):
    try:
        with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tmp:
            tmp_path = Path(tmp.name)
        with open(db_path, "rb") as src, open(tmp_path, "wb") as dst:
            dst.write(src.read())
        return tmp_path
    except Exception:
        return None

def _write_netscape_cookies(rows: list, out_path: Path) -> bool:
    try:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Auto-generated by Voxly\n\n")
            for (host, path, secure, expires, name, value) in rows:
                secure_str = "TRUE" if secure else "FALSE"
                include_sub = "TRUE" if host.startswith(".") else "FALSE"
                f.write(f"{host}\t{include_sub}\t{path}\t{secure_str}\t{expires}\t{name}\t{value}\n")
        return out_path.stat().st_size > 100
    except Exception:
        return False

def _extract_chromium_cookies_direct(browser: str, out_path: Path) -> bool:
    import sqlite3
    base = CHROMIUM_PROFILES.get(browser)
    if not base or not base.exists(): return False
    for sub in ("Default", "Profile 1", "Profile 2", ""):
        for rel in (Path("Network") / "Cookies", Path("Cookies")):
            db_path = base / sub / rel
            if not db_path.exists(): continue
            tmp_db = _copy_locked_db(db_path)
            if not tmp_db: continue
            try:
                conn = sqlite3.connect(f"file:{tmp_db}?mode=ro&immutable=1", uri=True)
                conn.row_factory = sqlite3.Row
                cur = conn.cursor()
                cur.execute("""
                    SELECT host_key, path, is_secure, expires_utc, name,
                           CASE WHEN length(value) > 0 THEN value ELSE '(encrypted)' END as value
                    FROM cookies
                    WHERE host_key LIKE '%youtube.com%' OR host_key LIKE '%google.com%'
                    ORDER BY host_key
                """)
                rows = cur.fetchall()
                conn.close()
                if not rows:
                    tmp_db.unlink(missing_ok=True)
                    continue
                EPOCH_DIFF = 11644473600
                cookie_rows = []
                for r in rows:
                    expires = max(0, r["expires_utc"] // 1_000_000 - EPOCH_DIFF)
                    cookie_rows.append((r["host_key"], r["path"], r["is_secure"], expires, r["name"], r["value"]))
                tmp_db.unlink(missing_ok=True)
                if _write_netscape_cookies(cookie_rows, out_path):
                    return True
            except Exception as e:
                logger.error(f"Cookie direct DB read failed for {browser}: {e}", exc_info=True)
                try: tmp_db.unlink(missing_ok=True)
                except: pass
    return False

def _try_extract_cookies(browser: str, out_path: Path) -> bool:
    try:
        r = subprocess.run(
            ["yt-dlp", "--cookies-from-browser", browser, "--cookies", str(out_path),
             "--skip-download", "--quiet", "--no-warnings",
             "https://www.youtube.com/watch?v=dQw4w9WgXcQ"],
            capture_output=True, timeout=20,
        )
        if r.returncode == 0 and out_path.exists() and out_path.stat().st_size > 200:
            return True
    except Exception:
        pass
    if browser != "firefox":
        if _extract_chromium_cookies_direct(browser, out_path):
            return True
    return False

def _auto_extract_cookies() -> bool:
    tmp_out = COOKIES_FILE.with_suffix(".tmp")
    browsers = ["chrome", "edge", "brave", "chromium", "opera", "vivaldi", "firefox"]
    for browser in browsers:
        logger.info(f"Cookie: Trying {browser}...")
        try:
            if browser != "firefox" and not _chromium_db_exists(browser):
                continue
            ok = _try_extract_cookies(browser, tmp_out)
            if ok:
                shutil.move(str(tmp_out), str(COOKIES_FILE))
                logger.info(f"Cookies auto-extracted from {browser} to cookies.txt")
                return True
        except Exception as e:
            logger.warning(f"Cookie: {browser} extraction failed: {e}")
        finally:
            if tmp_out.exists():
                try: tmp_out.unlink()
                except: pass
    logger.warning("Auto cookie extraction failed for all browsers.")
    return False

def _cookie_refresh_loop():
    while True:
        with _cookie_lock:
            success = _auto_extract_cookies()
            if not success and COOKIES_FILE.exists() and COOKIES_FILE.stat().st_size > 200:
                logger.info("Using previously saved cookies.txt")
                success = True
            if success:
                _cookie_ready.set()
            else:
                _cookie_ready.clear()
        time.sleep(COOKIE_REFRESH_SEC)

_cookie_thread = threading.Thread(target=_cookie_refresh_loop, daemon=True)
_cookie_thread.start()


def download_video(youtube_url: str) -> Path:
    uid = uuid.uuid4().hex[:10]
    template = str(DOWNLOADS_DIR / f"{uid}.%(ext)s")

    _cookie_ready.wait(timeout=25)

    cmd = [
        "yt-dlp",
        "-f", (
            "bestvideo[ext=mp4][height<=1080][fps<=60]"
            "+bestaudio[ext=m4a]"
            "/bestvideo[height<=1080]+bestaudio"
            "/bestvideo+bestaudio"
            "/best"
        ),
        "--merge-output-format", "mp4",
        "--format-sort", "res:1080,fps:60,ext:mp4,tbr",
        "--format-sort-force",
        "--no-playlist",
        "--no-part",
        "--extractor-args", "youtube:player_client=android,web",
        "--user-agent", "com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip",
        "--add-header", "Accept-Language:en-US,en;q=0.9",
        "-o", template,
    ]

    with _cookie_lock:
        if COOKIES_FILE.exists() and COOKIES_FILE.stat().st_size > 200:
            cmd += ["--cookies", str(COOKIES_FILE)]
            logger.info("Using cookies.txt for download")

    cmd.append(youtube_url)
    logger.info(f"Running download command: {' '.join(cmd)}")

    try:
        result = subprocess.run(cmd, capture_output=True, timeout=300)
    except subprocess.TimeoutExpired:
        raise RuntimeError("Download timed out after 5 minutes.")

    matches = list(DOWNLOADS_DIR.glob(f"{uid}*"))
    for ext in [".mp4", ".temp.mp4", ".mkv", ".webm"]:
        for m in matches:
            if m.name == f"{uid}{ext}":
                logger.info(f"Download found: {m.name}")
                return m

    if result.returncode != 0:
        stderr = result.stderr.decode(errors="replace")
        logger.error(f"yt-dlp failed:\n{stderr}")
        raise RuntimeError(f"Download failed:\n{stderr[-800:]}")

    if not matches:
        raise RuntimeError("yt-dlp finished but produced no output file.")
    return matches[0]
